spring:
  application:
    name: employee-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

  # Database
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/port
    username: nagesh
    password: nagesh
    driverClassName: org.postgresql.Driver

  config:
    import: "optional:configserver:http://localhost:8088"
